#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["HistoryService/HistoryService.csproj", "HistoryService/"]
COPY ["Monitoring/Monitoring.csproj", "Monitoring/"]
COPY ["SharedModels/SharedModels.csproj", "SharedModels/"]
RUN dotnet restore "HistoryService/HistoryService.csproj"
COPY . .
WORKDIR "/src/HistoryService"
RUN dotnet build "HistoryService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HistoryService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HistoryService.dll"]